### ISSUE TITLE
How do you consume this repo?

### ISSUE THREAD

**Issue by gsacavdm** [PacktPublishing/Optimizing-Databricks-Workload#3]
There's nothing in this repo but `ChapterXX` folders with some `.dbc` files that I have no idea what to do with.
There's no mention of these `.dbc` files in the readme nor in the book nor are there any other files in the repo.

**Comment by rajat-packt** [comment]
We have relayed your query to the author and we'll update you as soon as they back to us

**Comment by gsacavdm** [comment]
Nvm, I figured out that `.dbc` files are Databricks Notebooks that you can import.

It would be great for the book to call this out somewhere in the book, ideally the `Download the example code files` section of the book.
